server:  
  port: 8889  
eureka:  
  client:  
    service-url:  
      defaultZone: http://eureka:chunze1qaz2wsx@172.18.5.88:8761/eureka/,http://eureka:chunze1qaz2wsx@172.18.5.110:8761/eureka/
  instance:      
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:  
  application:  
      name: config-server
  cloud:  
    config:
      server:  
        git:  
          uri: https://github.com/helmsli/UnifiedConfiguration/
          search-paths: respo
          default-label: master
      label: master